### PR TITLE
Fix bug from improper handling of raketask string

### PR DESCRIPTION
**Pull request by purintai**
How to reproduce

1: put any raketask with arguments.

`lib/tasks/sometask.rake`
```ruby
task :sometask, ['spam', 'ham'] => :environment do |task, args|
    p args[:spam]
end
```

2: invoke raketask with arguments.

`bundle exec rake sometask\[egg\]`
or
`bundle exec rake "sometask[egg]"`

### CODE REVIEW

**Comment by mk** [comment]
Thanks!

**Comment by purintai** [comment]
Could you release it with tag branch?

**Comment by mk** [comment]
will do it when I'm back from holiday the week after next unless @msch or @kommen find the time to do it before then.

**Comment by purintai** [comment]
❤️

**Pull request merged**
